[project]
name = "yt-summarizer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.100.2",
    "requests>=2.32.5",
    "tiktoken>=0.11.0",
    "youtube-transcript-api>=1.2.2",
]
